### ISSUE TITLE
Add ' Publications'  tab

### ISSUE THREAD

**Issue by phuycke** [CogComNeuroSci/CogComNeuroSci.github.io#12]
# Goal

To add an extra tab referring to publications.   
For now, we will mirror the setup of the original website's [publication tab](https://cogcomneurosci.com/publications-page/)

**Comment by KateErgo** [comment]
In line with this idea, maybe a _Participate_ tab should also be added (with link to Sona)?

**Comment by phuycke** [comment]
@tomverguts In line with @KateErgo 's comment, perhaps we could also add a 'jobs' tag? Might become a mess though, we _already_ have 6 tags. Perhaps we can delete the 'github' tag (which redirects to our master branch), and add something else?

Solving [Issue #3](https://github.com/CogComNeuroSci/CogComNeuroSci.github.io/issues/3) might be useful here, as it allows us to store multiple subtags under one 'parent' tag.

**Comment by phuycke** [comment]
Publications tag was successfully added.   
The resulting page can be found [here](https://cogcomneurosci.github.io//publications/)
